#pragma once

#include <ESPAsyncWebServer.h>
#include "../config.h"
#include "../utils/nvs_manager.h"
#include "web_assets.h"   // generated by scripts/embed_web.py - do not edit

#include "../core/power_calculator.h"

class LimitManager;
class WiFiManager;

class WebSocketServer {
public:
  WebSocketServer();
  ~WebSocketServer();

  void begin(NVSManager &nvs,
             SystemData *sysData, SemaphoreHandle_t *mutex,
             PowerCalculator *powerCalc, LimitManager *limitMgr,
             WiFiManager *wifiMgr);
  void startServer();
  bool isRunning() const { return started; }
  void loop();

  // Live UI clients on /ws (Local dashboard, AP portal). Zero = nobody
  // watching over the LAN leg — one input of the eco-mode decision.
  size_t clientCount() const;

  void broadcastData(const SystemData &data);

  // Serves a file baked into flash by scripts/embed_web.py (the whole
  // dashboard PWA: index.html, style.css, script.js, manifest.json, sw.js,
  // icons). Returns false when the path is not an embedded asset so the caller
  // can fall through to a 404.
  //
  // This is what makes the board the whole application: the page is served
  // from http://192.168.4.1/, so its ws://192.168.4.1/ws is SAME-ORIGIN. The
  // old hosted-on-Firebase arrangement was https://, and a browser blocks
  // ws:// from an https page as mixed content - which is why the previous
  // read-only AP portal existed at all.
  static bool serveAsset(AsyncWebServerRequest *request);

  // Path lookup used by serveAsset(). Strips any "?v=..." cache-buster and
  // falls back to /index.html for "/" . Returns nullptr when unmatched.
  static const WebAsset *findAsset(const String &path);

private:
  AsyncWebServer *server;
  AsyncWebSocket *ws;
  NVSManager *nvs;

  PowerCalculator *powerCalc;
  SystemData *sysData;
  SemaphoreHandle_t *dataMutex;
  LimitManager *limitMgr;
  WiFiManager *wifiMgr;

  uint32_t lastBroadcast;
  bool started;

  void onWsEvent(AsyncWebSocket *server, AsyncWebSocketClient *client,
                 AwsEventType type, void *arg, uint8_t *data, size_t len);

  void handleCommand(AsyncWebSocketClient *client, const char *msg);

  void buildJson(const SystemData &data, String &json);
};
